- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/brew.yml
    - import_tasks: tasks/nvim.yml
    - import_tasks: tasks/dotfiles.yml

